// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("Updater")>]
[<assembly: AssemblyProductAttribute("Updater")>]
[<assembly: AssemblyCompanyAttribute("Dzmitry Martynau")>]
[<assembly: AssemblyDescriptionAttribute("Deploy, update and publish tools for Windows client applications.")>]
[<assembly: AssemblyVersionAttribute("0.2.20")>]
[<assembly: AssemblyFileVersionAttribute("0.2.20")>]
[<assembly: AssemblyInformationalVersionAttribute("0.2.20")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "Updater"
    let [<Literal>] AssemblyProduct = "Updater"
    let [<Literal>] AssemblyCompany = "Dzmitry Martynau"
    let [<Literal>] AssemblyDescription = "Deploy, update and publish tools for Windows client applications."
    let [<Literal>] AssemblyVersion = "0.2.20"
    let [<Literal>] AssemblyFileVersion = "0.2.20"
    let [<Literal>] AssemblyInformationalVersion = "0.2.20"
