// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("Updater.Publish")>]
[<assembly: AssemblyProductAttribute("Updater")>]
[<assembly: AssemblyCompanyAttribute("Dzmitry Martynau")>]
[<assembly: AssemblyDescriptionAttribute("Deploy, update and publish tools for Windows client applications.")>]
[<assembly: AssemblyVersionAttribute("0.2.19")>]
[<assembly: AssemblyFileVersionAttribute("0.2.19")>]
[<assembly: AssemblyInformationalVersionAttribute("0.2.19")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "Updater.Publish"
    let [<Literal>] AssemblyProduct = "Updater"
    let [<Literal>] AssemblyCompany = "Dzmitry Martynau"
    let [<Literal>] AssemblyDescription = "Deploy, update and publish tools for Windows client applications."
    let [<Literal>] AssemblyVersion = "0.2.19"
    let [<Literal>] AssemblyFileVersion = "0.2.19"
    let [<Literal>] AssemblyInformationalVersion = "0.2.19"
